first commit
LAV007/laboratory-work-j120 pull request #1
Opened 2020-05-15 15:12 UTC by LAV007

Николай Владимирович, здравствуйте! Посмотрите, пожалуйста, новые изменения в проекте.

2020-05-17 13:51 UTC, konivex requested changes
Замечания

ListOfOrderItems.setHowManyOrdered:
    if (howManyOrdered > product.getStockBalance())
    Должно выбрасываться исключение.

OrderManager.adddOrderPosition(Product product, int howMany):
    if (listOfOrderItems.contains(product)
    Должно выбрасываться исключение.

Класс Order: не хватает set-методов для отдельных атрибутов (contactPhoneNumber, discountPercentage и т.п.); обратие внимание, что атрибуты должны меняться только для готовящихся заказов.

Класс Configuration: его реализация (наличие метода getProperties()) может позволить случайно изменить значение к.-л. свойства. Лучше определить метод для возвращения конкретного свойства по заданному имени.

Класс SerializationDeserializationOfOrder: 
- общее замечание: если при чтении/записи произойдёт сбой, то файл останется открытым;
- метод doDeserialization(): файла может не быть, если система запускается первый раз.

Отмечу, то замечания к классу SerializationDeserializationOfOrder не применимы к классу WriteReadProductToFromList, он реализован корректно.

Не ясно назначение класса OrderManager в вашей реализации.
Также не ясно, как будут обрабатываться позиции заказа в процессе его подготовки. Видимо, для этого и предназначен класс OrderManager, но тогда он его код надо исправить соответствующим образом. Обращу внимание, что позиции заказа можно менять (добавлять новые, удалять имеющиеся, менять количество заказываемых единиц в позиции) до тех пор, пока заказ находится в состоянии "Готовится" (об этом же замечание к классу Order).

2020-05-17 13:51 UTC, konivex commented on src/ru/avalon/j120/order_accounting_system/auxiliary_classes/Product.java
> +        if(setPrice <= 0) System.err.println("There can't be a zero or negative price");// метод должен выбрасывать исключение
И где выброс исключения?

2020-05-17 13:51 UTC, konivex commented on src/ru/avalon/j120/order_accounting_system/auxiliary_classes/WareHouse.java
> +                JOptionPane.showMessageDialog(null, "The list almost contains the product with article " + product.getArticleNumber(),
Должно выбрасываться исключение!
Класс WareHouse не должен взаимодействовать с пользователем, это не его зона ответственности.

2020-05-20 07:51 UTC, LAV007 commented
Николай Владимирович, здравствуйте! Можете, пожалуйста, посмотреть пакет ui, я в телеграмм-группе описал вопрос.

> Николай Владимирович, здравствуйте! Пытаюсь реализовать добавление позиции заказа в таблицу, через диалоговое окно,  но в таком исполнении метода .addRow() из класса MyDataDialog.java строчки в таблицу не добавляются.
> 
> Если задать добавление строки в таблицу напрямую при нажатии на кнопку Ok в диалоговом окне - строчка добавится, но лишь та, которую непосредственно задам (комментарии в классе MyAbstrackModalDialog). 
> 
> Подскажите пожалуйста, где может быть ошибка?

2020-05-20 18:45 UTC, konivex commented
В конструкторе `MyAbstractModalDialog(Frame owner, String title)` вызов конструктора предка д.б. таким: `super(owner, title, true);`. Я когда показывал этот класс на демо, то сделал ошибку, вызвав сначала конструктор предка с двумя параметрами, но ближе к концу демо исправился, сделав его именно таким как здесь.

2020-05-20 19:06 UTC, LAV007 commented
Спасибо!!))  как я так не внимательно?..  Пишет!)

2020-05-20 19:19 UTC, LAV007 commented
Николай Владимирович, я же правильно понимаю: в классе ListDemo.java необходимо обработать объект orders типа JTable, похожим образом, как это сделано с объектом ordersItems типа JTable, только внутри (при отображение на графическом интерфейсе) должны быть текстовые поля для ввода данных о заказчике.

2020-05-21 07:57 UTC, konivex commented
Да, вы всё правильно понимаете, только данные должны обрабатываться не о "заказчике", а о заказе.

2020-05-24 09:02 UTC, LAV007 commented
Николай Владимирович, здравствуйте!
В последнем коммите по максимуму исправил ранее указанные недостатки. Не судите строго, сам понимаю, что работа совершенно сырая. Надеюсь такого минимального взаимодействия ui хватит для того, чтобы засчитать работу) и продолжить обучение на курсе.
Если быть честным, это, конечно, может быть мой недостаток, но я не совсем понимаю для чего учить (настолько плотно внедрять в модуль) swing, когда он уже давно не актуален. Он, может быть и является значительной составляющей стандартных пакетов, но точно не необходимым инструментом в современной разработке. Ввиду этого "непонимания", у меня просто напрочь отсутствовала какая-либо мотивация на то, чтобы выполнить это задание лучше, в сравнении с первым модулем, где я действительно приложил старания для выполнения лабораторных работ. Надеюсь, для будущих слушателей, учебный отдел разнообразит модули более свежими и востребованными на рынке библиотеками.  В противном случае, я просто не вижу смысла в старой программе. На мой взгляд, слушателей переподготовки необходимо готовить с прицелом на то, что после завершения обучения, выпускники будут востребованы на рынке, на не доучивать еще полгода самостоятельно новые библиотеки. Эти же мысли, я продублировал в отзыве за модуль, уж очень хочется, чтобы Политех был впереди планеты всей по качеству предоставляемых образовательных услуг!) Извините, за столь объемный комментарий. Спасибо!

2020-05-24 13:44 UTC, konivex commented
"ListOfOrderItems.setHowManyOrdered:
if (howManyOrdered > product.getStockBalance())
Должно выбрасываться исключение.": не исправлено.

"Класс Order: не хватает set-методов...": set-методы вы добавили, но не учли моё замечание "обратите внимание, что атрибуты должны меняться только для готовящихся заказов.". Исправьте.

SerializationDeserializationOfOrder.doDeserialization(): текущая логика работы метода такая: если файла нет, то создаём пустой ArrayList, а потом всё равно пытаемся читать файл. Думаете, такая логика верна? Так же замечу, что ссылку на созданный ArrayList вы сохраняете в локальную переменную, и теряете её тут же при выходе из блока "if(!file.exists())".

2020-05-27 18:18 UTC, konivex commented
SerializationDeserializationOfOrder.doDeserialization(): не в сторону исправили. Теперь когда у вас файла нет, то создаётся пустой файл, а потом вы из него читаете ArrayList, чего у вас не получится.

Исправьте последнее замечание.

2020-05-30 10:49 UTC, konivex commented
Алексей Викторович,
Не исправлено. Превращение переменной в поле класса для метода SerializationDeserializationOfOrder.doDeserialization() не меняет ничего. Он по-прежнему не будет работать. Прочтите ещё раз моё замечание и подумайте, что нужно исправить в тексте метода, чтобы он стал работать как надо.

2020-06-24 21:35 UTC, konivex requested changes
Для зачёта: добавьте в каждую таблицу две-три тестовые записи и сделайте так, чтобы приложение запускалось и показывало их в графическом интерфейсе.

Замечание: реализация класса DB (файл DB.java) будет приводить к большому количеству повисших соединений с базой данных. Исправьте.

2020-06-26 19:21 UTC, LAV007 commented
Николай Владимирович, видимо не только ЦП моего компа перегрелся... Исправил метод addPositions() из класса OrdersModel.java. Посмотрите, пожалуйста, когда будет время.

2020-06-27 12:14 UTC, konivex reviewed
Выглядит хорошо.
Встретимся в тимс завтра (в вс) в три и посмотрим.

2020-06-27 13:56 UTC, LAV007 commented
Добро, понял. Буду завтра в 15.00 в Teams!

2020-06-29 11:20 UTC, merged